#!/usr/bin/env bash
# i3 config file (v4)
#  Composer : Fenil Gandhi (ColdFire)
#  Sources  : On take whatever you like basis.

#   To-DO
#	
#	Fade-in Effects 
#   Change Color Themes
#   Select Utilities


##################################
#     First Things, First 
#################################
# Setup `Win` Key( Mod4 ) as Modifier
set $mod Mod4

set $terminal 			terminal
set $browser 			chromium
set $filemanager 		pcmanfm
set $texteditor			subl3

set $polybarscript 		~/.i3/polybar/launch.sh


set $flash 				exec --no-startup-id bash $flashscript
set $volup				exec --no-startup-id amixer sset Master 5%+; exec amixer sget  Master | grep -Po "\[[^%]+%\]" | tr '[\n]' ' ' | xargs -L 1 notify-send "Volume set to $1"
set $voldown 			exec --no-startup-id amixer sset Master 5%-; exec amixer sget  Master | grep -Po "\[[^%]+%\]" | tr '[\n]' ' ' | xargs -L 1 notify-send "Volume set to $1"
set $mute				exec --no-startup-id amixer sset Master toggle; exec amixer sget  Master | grep -Po "\[[^%]+%\]" | tr '[\n]' ' ' | xargs -L 1 notify-send "Volume set to $1"
set $lockscreen			~/.i3/i3lock-script.sh

#########################
#	Ui Settings
#########################
hide_edge_borders both
for_window [class="^.*"] border pixel 0
gaps inner 0
gaps outer 0
font xft:SFNS Display UltraLight 12  

##########################
#    Startup Sequence 
##########################
# { Auto-Lock, Sound, PAM, Wallpaper, Network, Power, Indian flag(Keyboard), Conky, Mount all drives, Polybar }
exec --no-startup-id xautolock -time 0 -locker exec $lockscreen
exec --no-startup-id volumeicon             
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec --no-startup-id nitrogen --restore; sleep 1; compton -b
exec --no-startup-id nm-applet
exec --no-startup-id xfce4-power-manager
exec --no-startup-id sbxkb
#exec --no-startup-id start_conky_green
exec --no-startup-id sudo mount -a
exec_always --no-startup-id $polybarscript
exec_always --no-startup-id ff-theme-util
exec_always --no-startup-id fix_xcursor

###########################
#
#  System Wide Shortcuts
#
############################
#--- General Applications ---#
	bindsym $mod+0x60 			[instance="dropdown"] scratchpad show; move position center
	bindsym $mod+Return 		exec --no-startup-id $terminal
	bindsym $mod+q				exec --no-startup-id $browser
	bindsym	$mod+w 				exec --no-startup-id $texteditor
	bindsym $mod+e 				exec --no-startup-id $filemanager
	bindsym $mod+space 			exec --no-startup-id rofi -show combi

#--- Common Functions ---#
	bindsym $mod+BackSpace		$flash
	bindsym Mod1+F4				kill
	bindsym Print 	       		exec --no-startup-id i3-scrot                       					
	bindsym $mod+Shift+Print --release exec --no-startup-id i3-scrot -s


#---  i3-gaps  ---#
	bindsym $mod+Shift++		gaps inner current plus 5
	bindsym $mod+Shift+-		gaps inner current minus 5
	bindsym $mod+Ctrl++			gaps outer current plus 5
	bindsym $mod+Ctrl+-			gaps outer current minus 5


#---  Defining Workspaces ---#
set $ws1  "1"
set $ws2  "2"
set $ws3  "3"
set $ws4  "4"
set $ws5  "5"
set $ws6  "6"
set $ws7  "7"
set $ws8  "8"
set $ws9  "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8

# Move focused container to workspace
bindsym $mod+Ctrl+1 move container to workspace $ws1
bindsym $mod+Ctrl+2 move container to workspace $ws2
bindsym $mod+Ctrl+3 move container to workspace $ws3
bindsym $mod+Ctrl+4 move container to workspace $ws4
bindsym $mod+Ctrl+5 move container to workspace $ws5
bindsym $mod+Ctrl+6 move container to workspace $ws6
bindsym $mod+Ctrl+7 move container to workspace $ws7
bindsym $mod+Ctrl+8 move container to workspace $ws8

# Move to workspace with focused container
bindsym $mod+Shift+1 move container to workspace $ws1; workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2; workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3; workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4; workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5; workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6; workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7; workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8; workspace $ws8

	

#--- Navigation and Focus ---#
	bindsym $mod+Tab		workspace prev
	bindsym $mod+Shift+Tab	workspace next
	bindsym $mod+x 			[urgent=latest] focus

	# Move Focus in Dir
	bindsym $mod+Left 			focus left
	bindsym $mod+Down 			focus down
	bindsym $mod+Up 			focus up
	bindsym $mod+Right 			focus right

	# Move Focused Window in Dir
	bindsym $mod+Shift+Left 	move left
	bindsym $mod+Shift+Down 	move down
	bindsym $mod+Shift+Up 		move up
	bindsym $mod+Shift+Right 	move right

	# split orientation
	bindsym $mod+h 		 		split h;exec notify-send 'tile horizontally'
	bindsym $mod+v 				split v;exec notify-send 'tile vertically'


#--- Layout Changes ---#
	# change container layout (stacked, tabbed, toggle split)
	bindsym $mod+F1 			layout stacking
	bindsym $mod+F2 			layout tabbed
	bindsym $mod+F3 			layout toggle split

	# toggle fullscreen mode for the focused container
	bindsym $mod+F11 			fullscreen toggle; exec notify-send 'Fullscreen Toggled'

	# toggle tiling / floating
	bindsym $mod+Shift+space 	floating toggle

	# Resize window (you can also use the mouse for that)
	bindsym $mod+r mode "resize"
	mode "resize" {
			# Pressing left will shrink the window’s width.
			# Pressing right will grow the window’s width.
			# Pressing up will shrink the window’s height.
			# Pressing down will grow the window’s height.

			bindsym Left resize shrink width 10 px or 10 ppt
			bindsym Right resize grow width 10 px or 10 ppt
			bindsym Up resize shrink height 10 px or 10 ppt
			bindsym Down resize grow height 10 px or 10 ppt

			# exit resize mode: Enter or Escape
			bindsym Return mode "default"
			bindsym Escape mode "default"
	}


#--- Intrusion Prevention ---#

	# Professor has arrived (Finally !!!)
	bindsym $mod+Delete	 exec $mute ; exec $pause ; workspace lmao ; exec $terminal -e htop ; exec $terminal -e screenfetch

	# Assholes Protection ( Lock screen ) 
	bindsym $mod+l exec $lockscreen

	# Time to test a new theme ( Restart i3 inplace )
	bindsym $mod+Shift+r 	restart


	# Set shut down, restart and locking features
	bindsym Mod1+Ctrl+Delete mode "$mode_system"
	set $mode_system (l)ogout, switch_(u)ser, (h)ibernate, (r)eboot, (s)hutdown, (n)one
	mode "$mode_system" {
		bindsym l exec --no-startup-id i3exit logout, mode "default"
		bindsym u exec --no-startup-id i3exit switch_user, mode "default"
		bindsym h exec --no-startup-id i3exit hibernate, mode "default"
		bindsym r exec --no-startup-id i3exit reboot, mode "default"
		bindsym s exec --no-startup-id i3exit shutdown, mode "default"
		bindsym n mode "default";exec notify-send "Nothing Done"

		# exit system mode: "Enter" or "Escape"
		bindsym Return mode "default"
		bindsym Escape mode "default"
	}



for_window [window_role="GtkFileChooserDialog"] resize shrink height 10 px
for_window [class="Sublime"] gaps outer 0


#Volume keys
bindsym $mod+plus		$volup
bindsym $mod+minus 		$voldown
bindsym XF86AudioLowerVolume	$voldown
bindsym XF86AudioRaiseVolume	$volup

###---Dropdown/Scratchpad Windows---###
#First I have a tmux window used for background scripts. I'll later bind this to mod+u.
for_window [instance="dropdown"] floating enable
for_window [instance="dropdown"] resize set 640 480
for_window [instance="dropdown"] move position center
for_window [instance="dropdown"] move scratchpad
exec --no-startup-id $terminal -name dropdown -e tmux

#exec chromium --incognito https://www.bobibanking.com